services:
  # Web Service hosting Django + Embedded 15-Minute Background Price Scraper
  - type: web
    name: ine-product-price-tracker
    runtime: python
    region: singapore
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn ine_scraper.wsgi:application --timeout 120 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
