services:
  # Web Service hosting the Django App
  - type: web
    name: ine-product-price-tracker
    runtime: python
    region: singapore
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn ine_scraper.wsgi:application --timeout 120 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false

  # Optional Background Cron Job for Price Scraping
  - type: cron
    name: ine-hourly-price-scraper-cron
    runtime: python
    region: singapore
    plan: free
    schedule: "*/15 * * * *"
    buildCommand: ./build.sh
    startCommand: python check_all_tracked_prices.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
