# Generated by Django 6.1.1 on 2026-09-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(help_text='Last 3 characters trimmed from p.title-sku', max_length=50, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=255)),
                ('raw_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
    ]
