# Generated by Django 6.1.1 on 2026-09-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_trackedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, help_text='Scraped integer product price', null=True),
        ),
    ]
