# Generated by Django 6.1.1 on 2026-09-20 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(help_text='Fetched product price')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when price was fetched')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='scraper.product')),
            ],
            options={
                'db_table': 'price_history',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
